[package]
name = "pumpfun_shred_sniper"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
sol-trade-router-sdk = { path = "../../crates/sdk" }
router_examples_common = { path = "../common" }
sol-parser-sdk = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
